# -*- coding: utf-8 -*-
"""llmbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z6GZmeFoGWDTDZcgaID9qozMVG4f6qHE
"""

import asyncio
from aiogram import Bot, Dispatcher, types, F
from aiogram.utils.formatting import Bold
from aiogram.utils.keyboard import ReplyKeyboardBuilder
from aiogram.filters import Command
from aiogram.types import FSInputFile
import sqlite3
import uuid
import matplotlib.pyplot as plt
import seaborn as sns
import random
import pandas as pd
from datetime import datetime
from generator import ResponseGenerator
from dotenv import load_dotenv
import os
import time
import traceback

from tech_metrics import log_pipeline_metrics

load_dotenv()

BOT_TOKEN = os.getenv("BOT_TOKEN")
HF_TOKEN = os.getenv("HF_TOKEN")
DATABASE = os.getenv("DATABASE", "data/users_data.db")
TECH_DATABASE = os.getenv("TECH_DATABASE", "data/tech.db")

bot = Bot(token=BOT_TOKEN)
database = DATABASE

resp_gen = ResponseGenerator(hf_token=HF_TOKEN)
dp = Dispatcher()


def main_markup():
    builder = ReplyKeyboardBuilder()
    builder.button(text="/help")
    builder.button(text="Задать вопрос")
    builder.adjust(*[1] * 2)
    markup = builder.as_markup(resize_keyboard=True)
    return markup


def reaction_markup():
    builder = ReplyKeyboardBuilder()
    builder.button(text="👍")
    builder.button(text="👎")
    builder.adjust(*[1] * 2)
    markup = builder.as_markup(resize_keyboard=True)
    return markup


@dp.message(Command("start"))
async def start(message: types.Message):
    connection = sqlite3.connect(database)
    user_id = connection.execute(
        "select user_id from users_chats where chat_id = ?",
        (str(message.chat.id),)
    ).fetchone()
    connection.close()

    if user_id is None:
        new_user_id = str(uuid.uuid4())
        connection = sqlite3.connect(database)
        connection.execute(
            "insert into users_chats(user_id, chat_id) values (?, ?)",
            (new_user_id, str(message.chat.id))
        )
        connection.commit()
        connection.close()

    await bot.send_message(
        message.chat.id,
        f"Привет, {message.chat.first_name}! Я – навигатор по кодексам. Чтобы узнать ограничения и подробности, нажми /help",
        reply_markup=main_markup()
    )


@dp.message(F.text == '👍')
async def like(message: types.Message):
    connection = sqlite3.connect(database)
    user_id = connection.execute(
        "select user_id from users_chats where chat_id = ?",
        (str(message.chat.id),)
    ).fetchone()
    connection.close()

    connection = sqlite3.connect(database)
    query_id = connection.execute(
        """
        select query_id
        from users_queries
        where user_id = ? and reaction_dttm is null
        order by query_dttm desc
        """,
        (user_id[0],)
    ).fetchone()
    connection.close()

    if not user_id or not query_id:
        await bot.send_message(message.chat.id, "Не удалось найти последний ответ для оценки.", reply_markup=main_markup())
        return

    reaction_dttm = datetime.now()
    print(user_id[0], query_id[0], reaction_dttm)

    connection = sqlite3.connect(database)
    connection.execute(
        "update users_queries set reaction_dttm = ?, like_flg = 1 where user_id = ? and query_id = ?",
        (str(reaction_dttm), user_id[0], query_id[0])
    )
    connection.commit()
    connection.close()

    await bot.send_message(message.chat.id, "Спасибо за высокую оценку!", reply_markup=main_markup())


@dp.message(F.text == '👎')
async def dislike(message: types.Message):
    connection = sqlite3.connect(database)
    user_id = connection.execute(
        "select user_id from users_chats where chat_id = ?",
        (str(message.chat.id),)
    ).fetchone()
    connection.close()

    connection = sqlite3.connect(database)
    query_id = connection.execute(
        """
        select query_id
        from users_queries
        where user_id = ? and reaction_dttm is null
        order by query_dttm desc
        """,
        (user_id[0],)
    ).fetchone()
    connection.close()

    if not user_id or not query_id:
        await bot.send_message(message.chat.id, "Не удалось найти последний ответ для оценки.", reply_markup=main_markup())
        return

    reaction_dttm = datetime.now()

    connection = sqlite3.connect(database)
    connection.execute(
        "update users_queries set reaction_dttm = ?, like_flg = 0 where user_id = ? and query_id = ?",
        (str(reaction_dttm), user_id[0], query_id[0])
    )
    connection.commit()
    connection.close()

    await bot.send_message(
        message.chat.id,
        "Жаль, что тебя не удовлетворил мой ответ. Попробуй спросить еще раз",
        reply_markup=main_markup()
    )


@dp.message(F.text == "Задать вопрос")
async def plot_wf(message: types.Message):
    chat_id = message.chat.id
    await bot.send_message(chat_id, 'Пожалуйста, введи свой запрос текстом', reply_markup=main_markup())


@dp.message(F.content_type.in_({'text'}))
async def mess(message: types.Message):
    text = message.text.lower()
    chat_id = message.chat.id

    if text == "/help":
        await bot.send_message(
            message.chat.id,
            f"Давай разбираться, {message.chat.first_name}!\nТы можешь мне направить вопрос, который связан с уголовным законодательством, и я постараюсь дать тебе на него ответ, используя информацию из официальных истончиков. После моего ответа ты можешь поставить лайк или дизлайк для оценки моего ответа.\n! Важно ! \nНа текущий момент я работаю только с УК РФ. Это значит, что во всех ответах тебе я буду ссылаться только на него, и даже если есть информация по твоему запросу в других кодексах и/или ФЗ, указах и других законодательных документах, то я не буду ее учитывать при своем ответе и стану использовать только статьи УК РФ. Если я не уверен в ответе, ты увидишь соответствующее сообщение.\nПомни, что я не являюсь заменой налоговому консультанту и мои советы не являются индивидуальной юридической рекомендацией",
            reply_markup=main_markup()
        )
        return

    request_id = str(uuid.uuid4())
    new_query_id = str(uuid.uuid4())
    query = message.text.lower()
    created_at = datetime.now().isoformat()

    overall_started = time.perf_counter()
    db_write_latency_sec = None
    send_latency_sec = None

    user_id = None
    answer = 'Я не обладаю достаточной информацией для ответа на данный вопрос. Пожалуйста, проконсультируйтесь с квалицицированным специалистом.'
    generation_metrics = {}

    try:
        await bot.send_message(chat_id, 'Думаю...', reply_markup=main_markup())

        connection = sqlite3.connect(database)
        row = connection.execute(
            "select user_id from users_chats where chat_id = ?",
            (str(message.chat.id),)
        ).fetchone()
        connection.close()

        if row is not None:
            user_id = row[0]

        answer, generation_metrics = resp_gen.generate(
            query,
            request_id=request_id
        )

        db_started = time.perf_counter()
        connection = sqlite3.connect(database)
        connection.execute(
            """
            insert into users_queries(
                user_id, query_id, query_dttm, query_txt, answer_txt, reaction_dttm, like_flg
            ) values (?, ?, ?, ?, ?, null, null)
            """,
            (user_id, new_query_id, created_at, query, answer)
        )
        connection.commit()
        connection.close()
        db_write_latency_sec = time.perf_counter() - db_started

        try:
            send_started = time.perf_counter()
            await bot.send_message(chat_id, answer, reply_markup=main_markup())
            send_latency_sec = time.perf_counter() - send_started
        except Exception as send_err:
            fallback_answer = 'Я не обладаю достаточной информацией для ответа на данный вопрос. Пожалуйста, проконсультируйтесь с квалицицированным специалистом.'
            send_started = time.perf_counter()
            await bot.send_message(chat_id, fallback_answer, reply_markup=main_markup())
            send_latency_sec = time.perf_counter() - send_started

            generation_metrics["pipeline_status"] = "fallback"
            generation_metrics["error_stage"] = "send_message"
            generation_metrics["error_type"] = type(send_err).__name__
            generation_metrics["error_message"] = str(send_err)

        await asyncio.sleep(1)
        await bot.send_message(
            chat_id,
            'Оцени мой ответ одной из кнопок снизу, это поможет мне стать лучше',
            reply_markup=reaction_markup()
        )

        total_latency_sec = time.perf_counter() - overall_started

        log_pipeline_metrics(
            request_id=request_id,
            created_at=created_at,
            user_id=user_id,
            chat_id=str(chat_id),
            query_id=new_query_id,
            question_text=query,

            pipeline_status=generation_metrics.get("pipeline_status", "success"),
            error_stage=generation_metrics.get("error_stage"),
            error_type=generation_metrics.get("error_type"),
            error_message=generation_metrics.get("error_message"),
            traceback_text=None,

            total_latency_sec=total_latency_sec,
            retrieval_latency_sec=generation_metrics.get("retrieval_latency_sec"),
            generation_latency_sec=generation_metrics.get("generation_latency_sec"),
            db_write_latency_sec=db_write_latency_sec,
            send_latency_sec=send_latency_sec,

            llm_provider=generation_metrics.get("llm_provider"),
            llm_model=generation_metrics.get("llm_model"),

            retrieval_k=generation_metrics.get("retrieval_k"),
            retrieved_docs_count=generation_metrics.get("retrieved_docs_count"),

            generation_attempts=generation_metrics.get("generation_attempts"),
            successful_attempt=generation_metrics.get("successful_attempt"),
            russian_only_flag=generation_metrics.get("russian_only_flag"),
            confidence_score=generation_metrics.get("confidence_score"),
            confidence_threshold=generation_metrics.get("confidence_threshold"),

            input_chars=generation_metrics.get("input_chars"),
            output_chars=generation_metrics.get("output_chars"),

            prompt_tokens=generation_metrics.get("prompt_tokens"),
            completion_tokens=generation_metrics.get("completion_tokens"),
            total_tokens=generation_metrics.get("total_tokens"),

            est_prompt_tokens=generation_metrics.get("est_prompt_tokens"),
            est_completion_tokens=generation_metrics.get("est_completion_tokens"),
            est_total_tokens=generation_metrics.get("est_total_tokens"),

            db_path=TECH_DATABASE
        )

    except Exception as e:
        total_latency_sec = time.perf_counter() - overall_started

        print(str(e))

        try:
            await bot.send_message(
                chat_id,
                'Произошла техническая ошибка. Попробуй перезапустить бота командой /start или повторить запрос позже.',
                reply_markup=main_markup()
            )
        except Exception:
            pass

        log_pipeline_metrics(
            request_id=request_id,
            created_at=created_at,
            user_id=user_id,
            chat_id=str(chat_id),
            query_id=new_query_id,
            question_text=query,

            pipeline_status="error",
            error_stage="unknown",
            error_type=type(e).__name__,
            error_message=str(e),
            traceback_text=traceback.format_exc(),

            total_latency_sec=total_latency_sec,
            retrieval_latency_sec=generation_metrics.get("retrieval_latency_sec") if generation_metrics else None,
            generation_latency_sec=generation_metrics.get("generation_latency_sec") if generation_metrics else None,
            db_write_latency_sec=db_write_latency_sec,
            send_latency_sec=send_latency_sec,

            llm_provider=generation_metrics.get("llm_provider") if generation_metrics else None,
            llm_model=generation_metrics.get("llm_model") if generation_metrics else None,

            retrieval_k=generation_metrics.get("retrieval_k") if generation_metrics else None,
            retrieved_docs_count=generation_metrics.get("retrieved_docs_count") if generation_metrics else None,

            generation_attempts=generation_metrics.get("generation_attempts") if generation_metrics else None,
            successful_attempt=generation_metrics.get("successful_attempt") if generation_metrics else None,
            russian_only_flag=generation_metrics.get("russian_only_flag") if generation_metrics else None,
            confidence_score=generation_metrics.get("confidence_score") if generation_metrics else None,
            confidence_threshold=generation_metrics.get("confidence_threshold") if generation_metrics else None,

            input_chars=len(query) if query else None,
            output_chars=None,

            prompt_tokens=generation_metrics.get("prompt_tokens") if generation_metrics else None,
            completion_tokens=generation_metrics.get("completion_tokens") if generation_metrics else None,
            total_tokens=generation_metrics.get("total_tokens") if generation_metrics else None,

            est_prompt_tokens=generation_metrics.get("est_prompt_tokens") if generation_metrics else None,
            est_completion_tokens=generation_metrics.get("est_completion_tokens") if generation_metrics else None,
            est_total_tokens=generation_metrics.get("est_total_tokens") if generation_metrics else None,

            db_path=TECH_DATABASE
        )


async def main():
    await dp.start_polling(bot)


if __name__ == "__main__":
    asyncio.run(main())